### ISSUE TITLE
Completion adding extra stuff with Omnisharp

### ISSUE THREAD

**Issue by BanchouBoo** [kak-lsp/kak-lsp#289]
![Completion example](https://user-images.githubusercontent.com/32691832/74186145-0c72d600-4c18-11ea-8546-eb26dfd44f8d.gif)

Relevant log: https://pastebin.com/XVc5dE9V

I'm not sure if this is a problem with kak-lsp itself or Omnisharp.

**Comment by billksun** [comment]
@BanchouBoo, sorry to hijack your issue, but how did you get omnisharp working?

**Comment by BanchouBoo** [comment]
@billksun I downloaded the release from the github page, pointed kak-lsp at the `run` file, and added `-lsp` as an argument. I think I may also have modified the run file to use the system-installed mono? Not sure, definitely modified something in the file though.

**Comment by billksun** [comment]
@BanchouBoo Ah thanks! I found your dot files repository, with very useful examples that helped me get C# and omnisharp working! After digging around, I realized my problem was because I don't have any filetype files for C# (I'm new to kak, pretty clueless). Would you be willing to contribute your `csharp.kak` file?

**Comment by BanchouBoo** [comment]
My `csharp.kak` file isn't really finished, and it does some pretty silly things, but feel free to use it, should be good enough.

**Comment by ul** [comment]
Could you confirm that you have this issue on the latest master? We added partial support for snippets some time ago. That extra stuff you see pasted is because language server is returning snippets and they are interpreted verbatim by your version of kak-lsp.

Also, you can ask language server not to send snippets by setting `snippet_support = false` in `kak-lsp.toml` (however, some language servers ignore it and send snippets anyway).

**Comment by BanchouBoo** [comment]
Most of the time none of the LSP stuff is working, and I can't really figure out why. But on the rare occasion that completion actually shows up, it indeed fills in how it's supposed to. Here's the log: https://hastebin.com/matisoqaru.rb

**Comment by topisani** [comment]
Should be solved with #616
