### ISSUE TITLE
support for scala metals ?

### ISSUE THREAD

**Issue by joeitu** [kak-lsp/kak-lsp#297]
Does kak-lsp support scala metals ? 
I have installed metals through vscode, but it doesn't seems to work with kak-lsp.
I didn't found any doc on metals or kak-lsp pages.

**Comment by joeitu** [comment]
related:
https://github.com/scalameta/metals-feature-requests/issues/91

**Comment by topisani** [comment]
It appears from that, that the issue is `kak-lsp` not supporting `window/showMessageRequest`. That should be fairly easy to implement

**Comment by ckipp01** [comment]
Thought I'd pipe in here as well after my comment in https://github.com/scalameta/metals-feature-requests/issues/91. I'd love to get kak documented and "supported", so I've gone ahead and started to test various features. I'm sure I'll find more as I play around, but I've got some initial thoughts and questions. I'll also add that I really enjoyed playing around with this so far :)

1. As was originally mentioned, `window/showMessageRequest` is important. This is what kicks off the entire process for metals to dump out the build definition that is needed to provide literally anything. We also use this for several other requests such as asking the user to add in a scalafmt version if they are missing one. Without it for example, `lsp-formatting` won't work. There is actually an issue for this already [here](https://github.com/ul/kak-lsp/issues/183), which is pretty old.

2. Metals relies pretty heavily on either `workspace/showMessage` being shown to the user. From what I can tell [here](https://github.com/ul/kak-lsp/blob/17fc6a6573251a77811ec7e75bf3807e24277cbb/src/controller.rs#L299-L311) the message should be shown via `lsp-show-message`, but I haven't seen any messages shown yet. Keep in mind I'm a noob with kak and kak-lsp, so I did the bare minimum to get everything up and running. Is there something specific I need to enable or add to see messages?

3. We also rely on the user being able to pass in configuration values. It looks like that's exactly what `lsp_server_configuration` is for, but I'm unable to get it to work. For example, I have the following in my `kakrc`.

```
hook global WinSetOption filetype=(scala) %{
  lsp-enable-window
  set global lsp_server_configuration metals.superMethodLenses=true
}
```
I would expect this to get set under `metals.superMethodLenses` which is what is illustrated in the readme, but the settings object is just empty for me. Is there something I'm missing here?

```json
[Trace - 09:34:03 PM] Received notification 'workspace/didChangeConfiguration'
Params: {
  "settings": {}
}
```

4. We also use `clientExperimentalCapabilities` for us to know what editors support various things that metals offers. We prefer this over server properties. I see [this referenced in the code](https://github.com/ul/kak-lsp/blob/4920bd1033375d67d157e143d039c21d6489a6bb/src/general.rs#L70-L71), but don't see an obvious way to set this. How would a user set this?

I'm more than happy on the Metals side of things to do what we need to do in order to support kak. I think it'd be a great addition. Let me know if there is anything I can do to help, and please let me know if I'm misunderstanding something mentioned above or doing something wrong.

**Comment by ckipp01** [comment]
Quick update that is relevant to this. We are just about to release a new version of Metals, and this newest version will be able to be configured pretty much fully via `initializationOptions` which addresses point 4 from above. Any one have thoughts on the other points that I brought up?

**Comment by geier1993** [comment]
I need scala for a project now. Just tried the newest version of kak-lsp (used with plugin manager....)
In the toml file I added
```
[language.scala]
filetypes = ["scala"]
roots = ["build.sbt"]
command = "metals"
```

I can
- list capabilities
- go to definitions (at least in a single file)
- format my buffer
- show informations & signatures
- rename symbols (at least in the same file)
- list project symbols (at least in the same file)
- highlight references

I have not tested more complex stuff and don't know how I can include more files - but for me this is already very helpful :)
