### ISSUE TITLE
Dart code completion injects spurious `${1:}`

### ISSUE THREAD

**Issue by haarts** [kak-lsp/kak-lsp#370]
Since upgrading from 7.0.0 to 8.0.0 whenever I code complete the characters `${1:}` are appended. 
![example](https://user-images.githubusercontent.com/10660/86588621-5627d880-bf8c-11ea-9975-f4cfe4a79c1b.png)

I do not have the same issue with Rust code. 

Kakoune version v2020.01.16-78-g3ef8a616
kak-lsp version 8.0.0
Dart VM version: 2.8.4 (stable)

**Comment by haarts** [comment]
I'm dying to have this resolved. How can I help with this?

**Comment by tw4452852** [comment]
I've encountered the same issue. After some investigation, the culprit is here:
https://github.com/ul/kak-lsp/blob/4aaa97260847f40da4da4407f132fb3dce41e247/rc/lsp.kak#L1458

It doesn't recognize the placeholder syntax provided by the dart language server, so I just did a hack for this, replacing the line above with this: `exec s((?<lt>!\\)(\\\\)*|\A)\K(\$(\d+|\{(\d+(:(\\\}|[^}])?)?)\}))<ret>`
