### ISSUE TITLE
What does "roots" mean in kak-lsp.toml?

### ISSUE THREAD

**Issue by maringuu** [kak-lsp/kak-lsp#411]
Hello!
Thank you for this great project!
In the README the `kak-lsp.toml` is told to be self explanatory. I didn't find any documentation about it and to me it is not clear what "roots" shall mean.
So, what does it mean?

**Comment by Ordoviz** [comment]
It is an array of filenames used to determine the root of a project directory structure.

**Comment by maringuu** [comment]
Great thanks!
Since `roots` is required to be given it looks like the lsp won't work if no files matching the ones in `roots` are found.
Is this the case?
And if not why is roots a mandatory argument?

**Comment by krobelus** [comment]
Since roots is required to be given it looks like the lsp won't work if no files matching the ones in roots are found.

@maringuu if no root is found, kak-lsp defaults to the buffer's directory. That's why it works if no root matches.

> And if not why is roots a mandatory argument?

It's probably better this way, because the buffer's directory may be subtly wrong sometimes. Recent kak-lsp versions also show an error in the editor when you are missing the `roots` parameter.
