### ISSUE TITLE
Feature request: lsp-code-action-sync

### ISSUE THREAD

**Issue by whereswaldon** [kak-lsp/kak-lsp#582]
Firstly, thanks to everyone who works on kak-lsp. You all save me so much time every day. :D

I'd like to request that a companion to the recent `:lsp-code-action` command be added that runs the code action synchronously. That would allow for use cases like using `gopls` to "Organize Imports" in a `BufWritePre` hook. Since the code actions are currently run asynchronously, the import rewrite currently may finish _after_ the buffer is written, which has all kinds of weird side effects.

Is this possible/easy to add?

**Comment by eliasnaur** [comment]
I tried

```
  define-command lsp-code-action-sync -params 1 -docstring "lsp-code-action <pattern>: perform the code action that matches the given regex" %{
      lsp-did-change-and-then "lsp-code-actions-request-sync true '%sh{printf %s ""$1"" | sed ""s/'/''/g""}'"
  }

  define-command -hidden lsp-code-actions-request-sync -params 1..2 -docstring "Request code actions for the main cursor position" %{
      evaluate-commands -no-hooks %sh{
  tmp=$(mktemp -q -d -t 'lsp-formatting.XXXXXX' 2>/dev/null || mktemp -q -d)
  pipe=${tmp}/fifo
  mkfifo ${pipe}

  code_action_pattern=""
  if [ $# -eq 2 ]; then
      code_action_pattern="codeActionPattern = \"$(printf %s "$2" | sed 's/\\/\\\\/g; s/"/\\"/g')\""
  fi

  (printf '
  session   = "%s"
  client    = "%s"
  buffile   = "%s"
  filetype  = "%s"
  version   = %d
  fifo      = "%s"
  method    = "textDocument/codeAction"
  [params]
  position.line     = %d
  position.column   = %d
  performCodeAction = %s
  %s
  ' "${kak_session}" "${kak_client}" "${kak_buffile}" "${kak_opt_filetype}" "${kak_timestamp}" "${fifo}" ${kak_cursor_line} ${kak_cursor_column} "$1" "$code_action_pattern" | eval   "${kak_opt_lsp_cmd} --request")

  cat ${pipe} | tee /tmp/pipe
  rm -rf ${tmp}
  }}
```

based on lsp-formatting-sync, but gave up (`lsp-code-action-sync "Organize Imports"` hangs).

**Comment by krobelus** [comment]
thanks for the report.
The fifo solution does not work because code actions (at least the ones sent by gopls) need two round trips.
- First the editor runs `lsp-apply-workspace-edit` to tell kak-lsp code action to execute
- kak-lsp converts the code action into a sequence of Kakoune edits and sends them back to the editor, to perform the edits.

but lsp-code-action-sync only reads from the fifo once, hence it will block.

We could probably work around this by avoiding the roundtrip (by computing code action edits eagerly),
but I'd rather fix this in a more general way, since we've had a report of
the same problem with lsp-formatting-sync (where roundtrips were caused by
`workspace/configuration` messages).

We probably need to make it so the fifo is only written to once everything else is done.

---

(I currently use goimports, which organizes imports automatically)

**Comment by krobelus** [comment]
I've implemented `lsp-code-action-sync` now, please try the `lsp-code-action-sync` branch (which is https://github.com/kak-lsp/kak-lsp/pull/583)

One thing I'm not sure about: should it throw an error if there is no matching code action?
I have added one now because it's easy to suppress with `try`

**Comment by krobelus** [comment]
Also keep in mind, while this works fine, there are probably limits to how much we can rely on code actions. They are designed for interactive use, not scripting.

**Comment by whereswaldon** [comment]
Thank you! It works as I expected, except that it seems to hang indefinitely if there are zero code actions available. Do you get that behavior as well? I would have thought it would error.

**Comment by krobelus** [comment]
it doesn't hang for me anymore, I get the error. I did have some mysterious hangs while working on it but can't reproduce them anymore.
Let me know if you have a reproducer. Make sure that you are using the right kak-lsp binary.

**Comment by whereswaldon** [comment]
While editing a go file, issue `:lsp-code-action-sync "Organize Imports"` when the imports list is already correct. This reproduces it for me 100% of the time.

I checked that I'm using the kak-lsp binary I built earlier today.

```
$ kak -version
Kakoune v2021.11.08-53-gf68e8313
$ gopls version
golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
```

**Comment by krobelus** [comment]
I've added a test in 3e83704 that shows that it can work.
You can run the test with `test/run test/gopls-code-action-sync.sh`. By default it tests the binary in target/debug/kak-lsp.

Maybe you sourced an old version of rc/lsp.kak (common problem when using plug.kak, I recommend manually eval'ing `kak-lsp --kakoune` instead when switching versions).

Or perhaps it's caused by your input project? I have only tested on toy Go files .

**Comment by krobelus** [comment]
Looks like vscode-go implements formatting [the same way, by running the "Organize Imports" code action on save](https://github.com/golang/vscode-go/blob/master/package.json#L189).
Would be much easier for us if everything was done by `textDocument/formatting`.

Our new lsp-code-action-sync allows

```kak
hook global WinSetOption filetype=go %{
	set-option buffer formatcmd gofmt
}
hook global BufWritePre .*[.]go %{
    try %{ lsp-code-action-sync '^Organize Imports$' }
    format
}
```

which seems to work fine.

It looks like the future is to use gopls's formatting instead of an external binary (there are loads of variants like gofmt/gofumpt/gofumptorts/goimports/goreturns; eventually gopls should supersede them all).
Sadly, the obvious implementation does not work:

```kak
hook -group my-format global BufWritePre .*[.]go %{
    try %{ lsp-code-action-sync '^Organize Imports$' }
    lsp-formatting-sync
}
```

if the buffer needs both import fixing and formatting, then the write happens before(!) formatting on my system.

This is because `lsp-formatting-sync` calls `lsp-did-change-and-then` which is async (if the document changed due to the earlier import fixes).
Synchronicity is viral, we cannot have an async link in our chain.
We could simply fix that by adding an lsp-did-change-and-then-sync but I'm starting to look for a more general solution.
Right now every *-sync command, even an internal ones like `lsp-apply-workspace-edit-sync` uses its own fifo.

Instead, we coujld just provide a global option `lsp_sync_fifo` that has the path to the fifo, which is used by every lsp command (includeing lsp-did-change-and-then).
Commands like `lsp-code-action-sync` will set that option to a temporary fifo, use a blocking read on it, and finally reset `lsp_sync_fifo`.
Since Kakoune is single-threaded, this will work fine; no one else will see the fifo.

Of course with just one pipe we can only have unidirectional communication. Currently we have

	lsp-code-action-sync
		From editor textDocument/codeAction
		To editor lsp-execute-command
			From editor workspace/executeCommand
			To editor lsp-apply-text-edits

but we can get elide/hide the workspace/executeCommand in this case, making this

	lsp-code-action-sync
		From editor textDocument/codeAction
		# run workspace/executeCommand behind the scenes
		To editor lsp-apply-text-edits

I think one roundtrip is enough for the *-sync commands, that just needs a bit of restructuring.

**Comment by krobelus** [comment]
OK some of my diagnosis was wrong. I went with a minimal fix, so https://github.com/kak-lsp/kak-lsp/pull/583 should work now.

I wonder what's the best way of shipping the BufWritePre hook by default (or at least documenting this trick, so users can find it).

**Comment by krobelus** [comment]
Ok I just found out when `lsp-code-action-sync` blocks: it's when LSP is not enabled.
Work around is to run `lsp-enable` manually.

The `*-sync` commands block the editor thread. Somehow this prevents us from automatically spawning a daemon.
We could at least improve the UI by just failing explicitly if lsp is not enabled..

**Comment by krobelus** [comment]
Fixing the sync commands if no server is running seems tricky, so I added an error message in 9e86141 (Declare that *-sync commands require a running server, 2022-01-03)

**Comment by whereswaldon** [comment]
@krobelus  Thank you for working so hard on this use-case! I'm able to fixup my imports quickly now, and it's a huge improvement to my workflow.
