### ISSUE TITLE
[Question] Is it possible to use "Extract into function" from Rust Analyzer?

### ISSUE THREAD

**Issue by lelgenio** [kak-lsp/kak-lsp#594]
Is it a code action that kak-lsp does not support or an external feature provided by each extension?

In vscode:
![image](https://user-images.githubusercontent.com/31388299/155893182-1430b703-ad5f-4a75-aef8-b7f95ac8467b.png)
![image](https://user-images.githubusercontent.com/31388299/155893157-dd338c16-b350-4750-9bcf-ab17894a00b1.png)
In Kakoune:
![image](https://user-images.githubusercontent.com/31388299/155893213-fb81e820-a494-45d7-a56f-b7e7138601cc.png)

**Comment by krobelus** [comment]
kak-lsp only sends the cursor position, but it should send the (main) selection coordinates (cursor position + anchor position)

I've fixed that on the `code-action-on-selection` branch.

Unfortunately, I get "Extract to variable" on your example instead of
"Extract to function". No idea why, I'll try to ask rust-analyzer folks.
Strangely, not even neovim seems to support this.
