### ISSUE TITLE
Investigate representing document symbols as a menu

### ISSUE THREAD

**Issue by ul** [kak-lsp/kak-lsp#63]
...to fuzzy search and jump. If it's not possible to make via Kakoune's menu then we should provide convenient way to allow integration with any fuzzy finder.

**Comment by maximbaz** [comment]
For an inspiration, here's a `rofi` integration for navigating through buffers and files in the current repo:

```
define-command rofi-files -docstring 'Open a file using Ag and Rofi' %{ %sh{
    FILE=$(ag --hidden -f -g "" | rofi -dmenu)
    [ -n "$FILE" ] && printf 'eval -client %%{%s} edit %%{%s}\n' "${kak_client}" "${FILE}" | kak -p "${kak_session}"
} }

define-command rofi-buffers -docstring 'Switch to a buffer using Rofi' %{ %sh{
    BUFFER=$(printf %s\\n "${kak_buflist}" | tr : '\n' | rofi -dmenu)
    [ -n "$BUFFER" ] && echo "eval -client '$kak_client' 'buffer ${BUFFER}'" | kak -p ${kak_session}
} }
```

**Comment by ul** [comment]
So I guess we just need to pass symbols as a list to `lsp-show-document-symbol` and then anyone will be able to write own integration by overriding `lsp-show-document-symbol` for which reasonable default still will be to put symbols into a dedicated buffer because it's the most portable way and doesn't require user to install specific tool.

**Comment by gustavo-hms** [comment]
Hi! I'm very interested in such a functionality, since I don't like the way `lsp-show-document-symbol` currently works (to many steps to reach the position where the symbol is in the document). What is missing to achieve it? I tried to follow the current implementation, but I miss a better understanding of both the `kak-lsp` code and Kakoune's plugins in general.

As I see it, we need a way to retrieve the list of symbols to pass it to the `-shell-script-candidates` in the command definition. For instance, the example given by @maximbaz can be easily implemented this way using plain Kakoune's tools:

```
define-command files -menu -params 1 \
    -shell-script-candidates %{ ag -f -g "" } %{ edit %arg{1} }
```

Then, I could make a simple mapping:
```
map global normal <F2> ': files '
```
to easily access it.

So, in theory we need a way to gather the list of symbols to define ` lsp-show-document-symbol` more or less like this:

```
define-command lsp-show-document-symbol -menu -params 1 \
    -shell-script-candidates %{ # The missing command here } \
    %{ # A way to get the line and the column of the chosen symbol }
```

This is portable and works for any installation.

Is this “missing command” hard to implement?

**Comment by krobelus** [comment]
implemented as `lsp-goto-document-symbol`, shortcut `s` (same as in Helix)
