### ISSUE TITLE
How to go to definition function start instead of select the whole function body?

### ISSUE THREAD

**Issue by theowenyoung** [kak-lsp/kak-lsp#643]
Hi, Thanks for the great plugin!

I have a question about going to the definition, I'm using deno as the language server, and every time I go to the definition, kak-lsp will select the whole function body. but I want to go to the function start point. I have tried:

```bash
map global lsp <d> "<esc>: lsp-definition<ret><a-;>gi" -docstring "go to definition"
```

it seems not to work.

**Comment by krobelus** [comment]
fixed, thanks for reporting!
your workaround doesn't work because `lsp-definition` is asynchronous (it sends a request to kak-lsp which eventually sends back a command via `kak -p`)
We do have some synchronous commands, its possible to write a synchronous definition request using `lsp-connect` but that's rather hacky, I think we should remove that feature.

**Comment by theowenyoung** [comment]
Thanks for the quick fix! I thought it was a feature...

**Comment by krobelus** [comment]
That feature wouldn't be necessary because you can press `<a-a><a-a>` (when using the [recommended mappings](https://github.com/kak-lsp/kak-lsp#configure-mappings)) to select the entire function. Though some temporary highlighting might make sense.

BTW I just pushed a fix that allows to use code actions (the lighbulb thing, shortcut `a` in the lsp user mode) with Deno.
