### ISSUE TITLE
Start LSP server with a lower CPU priority?

### ISSUE THREAD

**Issue by dpc** [kak-lsp/kak-lsp#646]
I am experiencing `kak` lagging with handling user input, most probably due to `rust-analyzer` doing some heavy CPU and IO work. It's very annoying and determinant to UX.

I've used `renice` to change the "niceness" of `rust-analyzer` process and it lead to immediate improvement. I don't really mind if things like auto-completion and suggestions are lagging a bit, as long as I can navigate the code without a lag.

So:

* Is there a good way to change how `kak-lsp` starts the LSP server (wrap it in `nice` or `chrt`) other than manually changing `command` for every language in `kak-lsp.toml`?
* Should `kak-lsp` default to doing so automatically somehow to get a better UX out of the box?

**Comment by krobelus** [comment]
I wonder what the bottleneck here is. We could try to measure how often rust-analyzer is sending us completions/diagnostics/progress reports, etc. Unlike other editors, Kakoune is single-threaded, so everything that ends up running Kakoune commands will block the UI thread ever so slightly.
I hope we can fix this, lowering the CPU priority seems like a band-aid solution (very cool that it helps though).

My wild guess its that this is because rust-analyzer sends loads of `$/progress` messages (sometimes dozens in a single millisecond). We already throttle them on the kak-lsp side - at most one every 50ms gets passed to Kakoune - but the limit might still be too low. Can you try if this patch helps?

```diff
diff --git a/src/progress.rs b/src/progress.rs
index c50ca906..041621bb 100644
--- a/src/progress.rs
+++ b/src/progress.rs
@@ -111,3 +111,3 @@ pub fn dollar_progress(meta: EditorMeta, params: Params, ctx: &mut Context) {
         ProgressParamsValue::WorkDone(WorkDoneProgress::Report(report)) => {
-            if ctx.work_done_progress_report_timestamp.elapsed() < Duration::from_millis(50) {
+            if ctx.work_done_progress_report_timestamp.elapsed() < Duration::from_millis(500) {
                 warn!("Progress report arrived too fast, dropping");
```

If that doesn't work can you maybe provide a log (indicating where it's slow) or steps to reproduce?

**Comment by dpc** [comment]
2 minutes in and it seems like a significant improvement. I'll report again if I hit any issues, otherwise please consider me happy with it. :)
