### ISSUE TITLE
Large input seems to be ignored

### ISSUE THREAD

**Issue by maximbaz** [kak-lsp/kak-lsp#75]
I continue to investigate bash-language-server 🙂

Install it (although for me the current version on npm [doesn't work](https://github.com/mads-hartmann/bash-language-server/issues/60), so maybe install the previous version `npm install -g bash-language-server@1.3.1`).

Open bash script, focus on e.g. `find` command and execute `:lsp-hover`.

What the language server will do in this case is it will return a huuuge amount of text, the output of `man find | col -b`. And this output somehow doesn't reach the kak-lsp, I see nothing in kakoune.

Whether it is right or wrong of the language server to produce so much output is a good question, but before I go deeper into investigating this, I just wanted to ask you - do you know if there is currently a limit in kak-lsp code that is ignoring large incoming messages? 

I guess the expected result in this case would be a trimmed message, i.e. define a max length, receive whatever the language server is sending, cut the received message, add ellipsis and show in the info box.

**Comment by ul** [comment]
At the moment kak-lsp doesn't pose any limits to message size, as well as doesn't do any trimming for better look. I just checked, message reaches Kakoune and `lsp-show-hover` is executed. I guess it's Kakoune's restriction on max info content length. We could figure it out and do trimming in `lsp-show-hover` itself (I'd prefer to do it here, and not in Rust code, because someone might want to override `lsp-show-hover` in his config and deal with full message in sensible way).

**Comment by ul** [comment]
https://github.com/mawww/kakoune/issues/2257
